name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Inputting "This is a sentence."
      id: inputting-this-is-a-sentence
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputting "This is a sentence."
        setup-command: ''
        command: python3 regex_replace_spaces/main.py
        input: This is a sentence.
        expected-output: This_is_a_sentence.
        comparison-method: exact
        timeout: 10
        max-score: 2
    - name: "Inputting \"Name\tAge\tLocation\""
      id: inputting-name-age-location
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: "Inputting \"Name\tAge\tLocation\""
        setup-command: ''
        command: python3 regex_replace_spaces/main.py
        input: "Name\tAge\tLocation"
        expected-output: Name_Age_Location
        comparison-method: exact
        timeout: 10
        max-score: 2
    - name: Inputting "  Too    many   spaces"
      id: inputting-too-many-spaces
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputting "  Too    many   spaces"
        setup-command: ''
        command: python3 regex_replace_spaces/main.py
        input: "  Too    many   spaces"
        expected-output: Too_many_spaces
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Inputting "HelloWorld"
      id: inputting-helloworld
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputting "HelloWorld"
        setup-command: ''
        command: python3 regex_replace_spaces/main.py
        input: HelloWorld
        expected-output: HelloWorld
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INPUTTING-THIS-IS-A-SENTENCE_RESULTS: "${{steps.inputting-this-is-a-sentence.outputs.result}}"
        INPUTTING-NAME-AGE-LOCATION_RESULTS: "${{steps.inputting-name-age-location.outputs.result}}"
        INPUTTING-TOO-MANY-SPACES_RESULTS: "${{steps.inputting-too-many-spaces.outputs.result}}"
        INPUTTING-HELLOWORLD_RESULTS: "${{steps.inputting-helloworld.outputs.result}}"
      with:
        runners: inputting-this-is-a-sentence,inputting-name-age-location,inputting-too-many-spaces,inputting-helloworld
